version: "3.8"

services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - frontend
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./volumes/uploads:/var/www/uploads
    networks:
      - student-crm

  api:
    build: ./api
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/student_crm
      - REDIS_URL=redis://redis:6379/0
      - MEILISEARCH_URL=http://meilisearch:7700
      - JWT_SECRET=${JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    depends_on:
      - postgres
      - redis
      - meilisearch
    volumes:
      - ./volumes/uploads:/app/uploads
    networks:
      - student-crm

  worker:
    build: ./worker
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/student_crm
      - REDIS_URL=redis://redis:6379/0
      - MEILISEARCH_URL=http://meilisearch:7700
    depends_on:
      - postgres
      - redis
      - meilisearch
    volumes:
      - ./volumes/uploads:/app/uploads
    networks:
      - student-crm

  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - student-crm

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=student_crm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - student-crm

  redis:
    image: redis:7-alpine
    volumes:
      - ./volumes/redis:/data
    ports:
      - "6379:6379"
    networks:
      - student-crm

  meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      - MEILI_ENV=production
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - ./volumes/meilisearch:/meili_data
    ports:
      - "7700:7700"
    networks:
      - student-crm

networks:
  student-crm:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  meilisearch_data:
  uploads:
